// Package dbcontext generates and stores a per-database Markdown "context file"
// that gives the AI Assistant a human-readable map of the schema. The file is
// auto-generated from introspection and then user-editable (the user can add
// business rules and column notes); the assistant always reads the current file.
package dbcontext

import (
	"fmt"
	"sort"
	"strings"

	"bigphant/internal/engine"
)

// Generate introspects the given database through the engine and renders a
// Markdown description: one section per table with its columns, types,
// nullability, keys, and indexes.
func Generate(eng engine.Engine, database string) (string, error) {
	tables, err := eng.ListTables(database)
	if err != nil {
		return "", err
	}
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })

	var b strings.Builder
	fmt.Fprintf(&b, "# Database context: %s\n\n", database)
	b.WriteString("> Auto-generated by Bigphant from the live schema. Edit freely to add ")
	b.WriteString("table/column descriptions and business rules — the AI Assistant reads this file. ")
	b.WriteString("Use \"Regenerate\" to re-sync the schema.\n>\n")
	b.WriteString("> Schemas use TOON (token-oriented) tables: a header line `name[count]{fields}:` ")
	b.WriteString("followed by one indented, comma-separated row per item. Values containing a ")
	b.WriteString("comma are double-quoted; an empty value means none.\n\n")
	fmt.Fprintf(&b, "%d table(s).\n", len(tables))

	for _, t := range tables {
		fmt.Fprintf(&b, "\n## %s\n", t.Name)
		if t.RowCount > 0 {
			fmt.Fprintf(&b, "rows: ~%d", t.RowCount)
			if t.Engine != "" {
				fmt.Fprintf(&b, " (%s)", t.Engine)
			}
			b.WriteByte('\n')
		}

		st, err := eng.DescribeTable(database, t.Name)
		if err != nil {
			fmt.Fprintf(&b, "_Could not describe table: %v_\n", err)
			continue
		}

		pk := map[string]bool{}
		for _, c := range st.PrimaryKey {
			pk[c] = true
		}

		fmt.Fprintf(&b, "columns[%d]{name,type,nullable,key,default,extra}:\n", len(st.Columns))
		for _, c := range st.Columns {
			null := "NO"
			if c.Nullable {
				null = "YES"
			}
			key := c.Key
			if pk[c.Name] && key == "" {
				key = "PRI"
			}
			def := ""
			if c.Default != nil {
				def = *c.Default
			}
			fmt.Fprintf(&b, "  %s,%s,%s,%s,%s,%s\n",
				toonCell(c.Name), toonCell(c.Type), null, key, toonCell(def), toonCell(c.Extra))
		}

		if len(st.PrimaryKey) > 0 {
			fmt.Fprintf(&b, "primary_key: %s\n", strings.Join(st.PrimaryKey, " "))
		}
		if len(st.Indexes) > 0 {
			fmt.Fprintf(&b, "indexes[%d]{name,unique,columns}:\n", len(st.Indexes))
			for _, idx := range st.Indexes {
				unique := "false"
				if idx.Unique {
					unique = "true"
				}
				fmt.Fprintf(&b, "  %s,%s,%s\n",
					toonCell(idx.Name), unique, toonCell(strings.Join(idx.Columns, " ")))
			}
		}
	}

	return b.String(), nil
}

// toonCell quotes a TOON value only when it would otherwise be ambiguous —
// i.e. it contains the comma delimiter, a quote, a newline, or edge whitespace.
// Empty values are emitted bare (an empty field means "none").
func toonCell(s string) string {
	if s == "" {
		return ""
	}
	if strings.ContainsAny(s, ",\"\n") || s != strings.TrimSpace(s) {
		s = strings.ReplaceAll(s, "\\", "\\\\")
		s = strings.ReplaceAll(s, "\"", "\\\"")
		return "\"" + s + "\""
	}
	return s
}
