// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {mysql} from '../models';
import {main} from '../models';
import {sqlbuilder} from '../models';
import {settings} from '../models';

export function CreateConnection(arg1:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteRows(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<number>;

export function DescribeTable(arg1:string,arg2:string):Promise<mysql.TableStructure>;

export function ExecuteRaw(arg1:string,arg2:main.ExecOptions):Promise<mysql.RawResult>;

export function FetchRows(arg1:sqlbuilder.FetchRowsRequest):Promise<mysql.ResultSet>;

export function GetSettings():Promise<settings.AppSettings>;

export function InsertRow(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function ListConnections():Promise<Array<connections.ConnectionMeta>>;

export function ListDatabases():Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<mysql.TableSummary>>;

export function OpenConnection(arg1:string):Promise<void>;

export function ServerVersion():Promise<string>;

export function TestConnection(arg1:connections.ConnectionInput):Promise<main.TestResult>;

export function UpdateConnection(arg1:string,arg2:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function UpdateRow(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;
