// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AlterTable(arg1, arg2) {
  return window['go']['main']['App']['AlterTable'](arg1, arg2);
}

export function CommitTransaction() {
  return window['go']['main']['App']['CommitTransaction']();
}

export function ConfirmQuitClose() {
  return window['go']['main']['App']['ConfirmQuitClose']();
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeactivateLicenseDevice(arg1) {
  return window['go']['main']['App']['DeactivateLicenseDevice'](arg1);
}

export function DeactivateThisDevice() {
  return window['go']['main']['App']['DeactivateThisDevice']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRows'](arg1, arg2, arg3);
}

export function DescribeTable(arg1, arg2) {
  return window['go']['main']['App']['DescribeTable'](arg1, arg2);
}

export function EntityDefinition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EntityDefinition'](arg1, arg2, arg3, arg4);
}

export function ExecuteRaw(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRaw'](arg1, arg2);
}

export function ExportRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportRows'](arg1, arg2, arg3);
}

export function FetchRows(arg1) {
  return window['go']['main']['App']['FetchRows'](arg1);
}

export function ForceValidateLicense() {
  return window['go']['main']['App']['ForceValidateLicense']();
}

export function GetCheckoutURL() {
  return window['go']['main']['App']['GetCheckoutURL']();
}

export function GetLicense() {
  return window['go']['main']['App']['GetLicense']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function LicenseActivated() {
  return window['go']['main']['App']['LicenseActivated']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListEntities(arg1) {
  return window['go']['main']['App']['ListEntities'](arg1);
}

export function ListLicenseDevices() {
  return window['go']['main']['App']['ListLicenseDevices']();
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function PreviewAlterTable(arg1) {
  return window['go']['main']['App']['PreviewAlterTable'](arg1);
}

export function RemoveLicense() {
  return window['go']['main']['App']['RemoveLicense']();
}

export function RequestFreeLicense(arg1) {
  return window['go']['main']['App']['RequestFreeLicense'](arg1);
}

export function RollbackTransaction() {
  return window['go']['main']['App']['RollbackTransaction']();
}

export function SchemaColumns(arg1) {
  return window['go']['main']['App']['SchemaColumns'](arg1);
}

export function ServerFlavor() {
  return window['go']['main']['App']['ServerFlavor']();
}

export function ServerVersion() {
  return window['go']['main']['App']['ServerVersion']();
}

export function SetActiveDatabase(arg1) {
  return window['go']['main']['App']['SetActiveDatabase'](arg1);
}

export function SetConnectionEditMode(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionEditMode'](arg1, arg2);
}

export function ShouldInterceptClose() {
  return window['go']['main']['App']['ShouldInterceptClose']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
