// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {sqlbuilder} from '../models';
import {dbtypes} from '../models';
import {connections} from '../models';
import {main} from '../models';
import {settings} from '../models';

export function ActivateLicense(arg1:string):Promise<license.Info>;

export function AlterTable(arg1:sqlbuilder.AlterTableRequest,arg2:boolean):Promise<dbtypes.RawResult>;

export function CommitTransaction():Promise<void>;

export function ConfirmQuitClose():Promise<void>;

export function CreateConnection(arg1:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function DeactivateLicenseDevice(arg1:string):Promise<void>;

export function DeactivateThisDevice():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteRows(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<number>;

export function DescribeTable(arg1:string,arg2:string):Promise<dbtypes.TableStructure>;

export function EntityDefinition(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExecuteRaw(arg1:string,arg2:main.ExecOptions):Promise<dbtypes.RawResult>;

export function ExportRows(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FetchRows(arg1:sqlbuilder.FetchRowsRequest):Promise<dbtypes.ResultSet>;

export function ForceValidateLicense():Promise<license.Info>;

export function GetCheckoutURL():Promise<string>;

export function GetLicense():Promise<license.Info>;

export function GetSettings():Promise<settings.AppSettings>;

export function InsertRow(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function LicenseActivated():Promise<boolean>;

export function ListConnections():Promise<Array<connections.ConnectionMeta>>;

export function ListDatabases():Promise<Array<string>>;

export function ListEntities(arg1:string):Promise<Array<dbtypes.Entity>>;

export function ListLicenseDevices():Promise<Array<license.Device>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<dbtypes.TableSummary>>;

export function OpenConnection(arg1:string):Promise<void>;

export function PreviewAlterTable(arg1:sqlbuilder.AlterTableRequest):Promise<main.AlterPreview>;

export function RemoveLicense():Promise<void>;

export function RequestFreeLicense(arg1:string):Promise<void>;

export function RollbackTransaction():Promise<void>;

export function SchemaColumns(arg1:string):Promise<Record<string, Array<string>>>;

export function ServerFlavor():Promise<string>;

export function ServerVersion():Promise<string>;

export function SetActiveDatabase(arg1:string):Promise<void>;

export function SetConnectionEditMode(arg1:string,arg2:string):Promise<connections.ConnectionMeta>;

export function ShouldInterceptClose():Promise<boolean>;

export function TestConnection(arg1:connections.ConnectionInput):Promise<main.TestResult>;

export function UpdateConnection(arg1:string,arg2:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function UpdateRow(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;
