// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitTransaction() {
  return window['go']['main']['App']['CommitTransaction']();
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRows'](arg1, arg2, arg3);
}

export function DescribeTable(arg1, arg2) {
  return window['go']['main']['App']['DescribeTable'](arg1, arg2);
}

export function ExecuteRaw(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRaw'](arg1, arg2);
}

export function FetchRows(arg1) {
  return window['go']['main']['App']['FetchRows'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function RollbackTransaction() {
  return window['go']['main']['App']['RollbackTransaction']();
}

export function SchemaColumns(arg1) {
  return window['go']['main']['App']['SchemaColumns'](arg1);
}

export function ServerVersion() {
  return window['go']['main']['App']['ServerVersion']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
