// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAssistantStatus(arg1) {
  return window['go']['main']['App']['AIAssistantStatus'](arg1);
}

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AlterTable(arg1, arg2) {
  return window['go']['main']['App']['AlterTable'](arg1, arg2);
}

export function ApplyGrants(arg1) {
  return window['go']['main']['App']['ApplyGrants'](arg1);
}

export function CommitTransaction() {
  return window['go']['main']['App']['CommitTransaction']();
}

export function ConfirmQuitClose() {
  return window['go']['main']['App']['ConfirmQuitClose']();
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateDatabase(arg1) {
  return window['go']['main']['App']['CreateDatabase'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeactivateLicenseDevice(arg1) {
  return window['go']['main']['App']['DeactivateLicenseDevice'](arg1);
}

export function DeactivateThisDevice() {
  return window['go']['main']['App']['DeactivateThisDevice']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRows'](arg1, arg2, arg3);
}

export function DescribeTable(arg1, arg2) {
  return window['go']['main']['App']['DescribeTable'](arg1, arg2);
}

export function DropUser(arg1, arg2) {
  return window['go']['main']['App']['DropUser'](arg1, arg2);
}

export function EnableAIAssistant(arg1) {
  return window['go']['main']['App']['EnableAIAssistant'](arg1);
}

export function EntityDefinition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EntityDefinition'](arg1, arg2, arg3, arg4);
}

export function ExecuteRaw(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRaw'](arg1, arg2);
}

export function ExportRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportRows'](arg1, arg2, arg3);
}

export function FetchRows(arg1) {
  return window['go']['main']['App']['FetchRows'](arg1);
}

export function ForceValidateLicense() {
  return window['go']['main']['App']['ForceValidateLicense']();
}

export function GenerateDBContext(arg1) {
  return window['go']['main']['App']['GenerateDBContext'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetCheckoutURL() {
  return window['go']['main']['App']['GetCheckoutURL']();
}

export function GetDBContext(arg1) {
  return window['go']['main']['App']['GetDBContext'](arg1);
}

export function GetLicense() {
  return window['go']['main']['App']['GetLicense']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function LicenseActivated() {
  return window['go']['main']['App']['LicenseActivated']();
}

export function ListAIModels() {
  return window['go']['main']['App']['ListAIModels']();
}

export function ListActivity() {
  return window['go']['main']['App']['ListActivity']();
}

export function ListCharsets() {
  return window['go']['main']['App']['ListCharsets']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListEntities(arg1) {
  return window['go']['main']['App']['ListEntities'](arg1);
}

export function ListGrants(arg1, arg2) {
  return window['go']['main']['App']['ListGrants'](arg1, arg2);
}

export function ListLicenseDevices() {
  return window['go']['main']['App']['ListLicenseDevices']();
}

export function ListLocks() {
  return window['go']['main']['App']['ListLocks']();
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function PickSQLiteFile() {
  return window['go']['main']['App']['PickSQLiteFile']();
}

export function PreviewAlterTable(arg1) {
  return window['go']['main']['App']['PreviewAlterTable'](arg1);
}

export function RemoveLicense() {
  return window['go']['main']['App']['RemoveLicense']();
}

export function RequestFreeLicense(arg1) {
  return window['go']['main']['App']['RequestFreeLicense'](arg1);
}

export function RollbackTransaction() {
  return window['go']['main']['App']['RollbackTransaction']();
}

export function RunMaintenance(arg1, arg2) {
  return window['go']['main']['App']['RunMaintenance'](arg1, arg2);
}

export function SaveDBContext(arg1, arg2) {
  return window['go']['main']['App']['SaveDBContext'](arg1, arg2);
}

export function SchemaColumns(arg1) {
  return window['go']['main']['App']['SchemaColumns'](arg1);
}

export function ServerCapabilities() {
  return window['go']['main']['App']['ServerCapabilities']();
}

export function ServerFlavor() {
  return window['go']['main']['App']['ServerFlavor']();
}

export function ServerVersion() {
  return window['go']['main']['App']['ServerVersion']();
}

export function SetAIConfig(arg1, arg2) {
  return window['go']['main']['App']['SetAIConfig'](arg1, arg2);
}

export function SetActiveDatabase(arg1) {
  return window['go']['main']['App']['SetActiveDatabase'](arg1);
}

export function SetConnectionEditMode(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionEditMode'](arg1, arg2);
}

export function ShouldInterceptClose() {
  return window['go']['main']['App']['ShouldInterceptClose']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
