// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {license} from '../models';
import {sqlbuilder} from '../models';
import {dbtypes} from '../models';
import {connections} from '../models';
import {settings} from '../models';
import {ai} from '../models';

export function AIAssistantStatus(arg1:string):Promise<main.AIStatus>;

export function AIChat(arg1:main.AIChatRequest):Promise<main.AIChatResponse>;

export function ActivateLicense(arg1:string):Promise<license.Info>;

export function AlterTable(arg1:sqlbuilder.AlterTableRequest,arg2:boolean):Promise<dbtypes.RawResult>;

export function ApplyGrants(arg1:dbtypes.GrantRequest):Promise<void>;

export function CommitTransaction():Promise<void>;

export function ConfirmQuitClose():Promise<void>;

export function CreateConnection(arg1:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function CreateDatabase(arg1:dbtypes.CreateDatabaseRequest):Promise<void>;

export function CreateUser(arg1:dbtypes.CreateUserRequest):Promise<void>;

export function DeactivateLicenseDevice(arg1:string):Promise<void>;

export function DeactivateThisDevice():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteRows(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<number>;

export function DescribeTable(arg1:string,arg2:string):Promise<dbtypes.TableStructure>;

export function DropUser(arg1:string,arg2:string):Promise<void>;

export function EnableAIAssistant(arg1:string):Promise<main.AIEnableResult>;

export function EntityDefinition(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExecuteRaw(arg1:string,arg2:main.ExecOptions):Promise<dbtypes.RawResult>;

export function ExportRows(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FetchRows(arg1:sqlbuilder.FetchRowsRequest):Promise<dbtypes.ResultSet>;

export function ForceValidateLicense():Promise<license.Info>;

export function GenerateDBContext(arg1:string):Promise<string>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetCheckoutURL():Promise<string>;

export function GetDBContext(arg1:string):Promise<string>;

export function GetLicense():Promise<license.Info>;

export function GetSettings():Promise<settings.AppSettings>;

export function InsertRow(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function KillProcess(arg1:string):Promise<void>;

export function LicenseActivated():Promise<boolean>;

export function ListAIModels():Promise<Array<ai.Model>>;

export function ListActivity():Promise<Array<dbtypes.ServerProcess>>;

export function ListCharsets():Promise<Array<dbtypes.Charset>>;

export function ListConnections():Promise<Array<connections.ConnectionMeta>>;

export function ListDatabases():Promise<Array<string>>;

export function ListEntities(arg1:string):Promise<Array<dbtypes.Entity>>;

export function ListGrants(arg1:string,arg2:string):Promise<Array<dbtypes.Grant>>;

export function ListLicenseDevices():Promise<Array<license.Device>>;

export function ListLocks():Promise<Array<dbtypes.LockInfo>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<dbtypes.TableSummary>>;

export function ListUsers():Promise<Array<dbtypes.ServerUser>>;

export function OpenConnection(arg1:string):Promise<void>;

export function PickSQLiteFile():Promise<string>;

export function PreviewAlterTable(arg1:sqlbuilder.AlterTableRequest):Promise<main.AlterPreview>;

export function RemoveLicense():Promise<void>;

export function RequestFreeLicense(arg1:string):Promise<void>;

export function RollbackTransaction():Promise<void>;

export function RunMaintenance(arg1:string,arg2:string):Promise<dbtypes.RawResult>;

export function SaveDBContext(arg1:string,arg2:string):Promise<void>;

export function SchemaColumns(arg1:string):Promise<Record<string, Array<string>>>;

export function ServerCapabilities():Promise<dbtypes.ServerCapabilities>;

export function ServerFlavor():Promise<string>;

export function ServerVersion():Promise<string>;

export function SetAIConfig(arg1:string,arg2:string):Promise<void>;

export function SetActiveDatabase(arg1:string):Promise<void>;

export function SetConnectionEditMode(arg1:string,arg2:string):Promise<connections.ConnectionMeta>;

export function SetTheme(arg1:string):Promise<void>;

export function ShouldInterceptClose():Promise<boolean>;

export function TestConnection(arg1:connections.ConnectionInput):Promise<main.TestResult>;

export function UpdateConnection(arg1:string,arg2:connections.ConnectionInput):Promise<connections.ConnectionMeta>;

export function UpdateRow(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Record<string, any>):Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;
